networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
services:
  mongodb:
    image: mongodb:1.0.0
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - mongodb: /data/db
  redis:
    image: redis:1.0.0
    container_name: redis
    networks:
      - roboshop
    volumes:
      - redis: /data
  catalogue:
    image: catalogue:1.0.0
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  user:
    image: user:1.0.0
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  cart:
    image: cart:1.0.0
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis
  web:
    image: web:1.0.0
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
      - cart
      - user
    ports:
      - "8080:80"