apiVersion: v1
kind: Pod
metadata: 
  name: resources
  labels:
    project: roboshop
sepc:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - name: http
      containerPort: 80