apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    project: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: mongodb
    ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: http