apiVersion: v1
kind: Service
metadata: 
  name: service-loadbalancer
  labels:
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    component: web
  ports:
  - name: service-port
    port: 80
    targetPort: web-port
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    project: roboshop
    environment: dev
    component: web
spec:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
    - name: web-port
      containerPort: 80
